### ISSUE TITLE
Query releasing data race may end in a SIGSEGV

### ISSUE THREAD

**Issue by emile-tawfik** [apache/cassandra-gocql-driver#1269]
### What version of Cassandra are you using?
`3.11.2`

### What version of Gocql are you using?
ec4793573d1447b6f92a1b359a0594566fad9d0e

### What did you do?
I tried to release a query without iterating to the end.

### What did you expect to see?
Nothing.

### What did you see instead?
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6de7a2]

goroutine 336 [running]:
gitlab.com/nexttv/backend/vendor/github.com/gocql/gocql.(*Session).Closed(0x0, 0xc000034000)
	/home/tawfike/go/src/gitlab.com/nexttv/backend/vendor/github.com/gocql/gocql/session.go:395 +0x22
gitlab.com/nexttv/backend/vendor/github.com/gocql/gocql.(*Session).executeQuery(0x0, 0xc0004f5b80, 0x10)
	/home/tawfike/go/src/gitlab.com/nexttv/backend/vendor/github.com/gocql/gocql/session.go:403 +0x2f
gitlab.com/nexttv/backend/vendor/github.com/gocql/gocql.(*nextIter).fetch.func1()
	/home/tawfike/go/src/gitlab.com/nexttv/backend/vendor/github.com/gocql/gocql/session.go:1483 +0x3e
sync.(*Once).Do(0xc00012af70, 0xc0003fa7b0)
	/usr/lib/go/src/sync/once.go:44 +0xb3
gitlab.com/nexttv/backend/vendor/github.com/gocql/gocql.(*nextIter).fetch(0xc00012af60, 0xc000438f68)
	/home/tawfike/go/src/gitlab.com/nexttv/backend/vendor/github.com/gocql/gocql/session.go:1482 +0x54
created by gitlab.com/nexttv/backend/vendor/github.com/gocql/gocql.(*Iter).Scan
	/home/tawfike/go/src/gitlab.com/nexttv/backend/vendor/github.com/gocql/gocql/session.go:1376 +0x547
```
---

### Additional information
The crash occur when the release is made just before a "page switch".
If I disable auto paging and make it manually no data race occur.

Just wanted to point this out, I don't know if this behavior is expected.

**Comment by alourie** [comment]
@emile-tawfik can you show the example code? This error just shows that for some reason something is nil instead of a pointer; does this happen when the query is released (i.e. closed) before you finished working with the iterator?

If that's the case, I'd say it's expected. The question though if it's the proper way to handle things. I'd love to see your client code to understand this more.

**Comment by mmatczuk** [comment]
Did someone measure the benefit of pooling of Query objects?

**Comment by emile-tawfik** [comment]
@alourie This happend when the query is released and closed before finished working with the iterator.
```golang
query := session.Query("CREATE TABLE IF NOT EXISTS whatever (id bigint, somefield bigint, PRIMARY KEY (id, somefield));")
	err = query.Exec()
	query.Release()
	if err != nil {
		t.Fatal(err)
	}
	b := gocql.NewBatch(gocql.LoggedBatch)
	insertStmt := "INSERT INTO whatever (id, somefield) VALUES (?, ?) "
	b.Query(insertStmt, 1, 1)
	b.Query(insertStmt, 1, 2)
	b.Query(insertStmt, 1, 3)
	b.Query(insertStmt, 1, 4)
	b.Query(insertStmt, 1, 5)
	b.Query(insertStmt, 1, 6)
	err = session.ExecuteBatch(b)
	if err != nil {
		t.Fatal(err)
	}
	query = session.Query("SELECT id, somefield FROM whatever WHERE id = ?", 1).PageSize(2)
	iter := query.Iter()
	var id, somefield uint64
	for iter.Scan(&id, &somefield) {
		fmt.Println("ROW", id, somefield)
		if iter.WillSwitchPage() {
			break
		}
	}
	fmt.Println(iter.Close())
	query.Release()
```

**Comment by alourie** [comment]
@emile-tawfik I ran the example above and had no data race. Only if I close the `iter` and then try to fetch the next page I get the similar `sigsegv` error, which makes sense. Is there anything special about how the keyspace is set?

**Comment by emile-tawfik** [comment]
Nothing special about the keyspace.

**Comment by alourie** [comment]
@emile-tawfik there is no real relation between the `query` and `iter` objects in the code, so I can't see why would releasing the query affect the iteration. And I've tried to run your example again, and see no data races whatsoever.

**Comment by emile-tawfik** [comment]
@alourie maybe you need to add a `time.Sleep(time.Second)` after the last line of my example in order to get the segfault.

It seem that the segfault happen in this go routine https://github.com/gocql/gocql/blob/master/session.go#L1362

**Comment by blkmlk** [comment]
@alourie we got SIGSEGV too but we didn't close an iterator before release an query. Must iter be closed?

**Comment by blkmlk** [comment]
@alourie We gеt situation when gocql invokes `go iter.next.fetch()` in session.go:1363 and an another  goroutine calls query.Release(), for example by defer. As a result query's field "m" sets to nil and we get panic with "nil pointer dereference" message in session.go:1519. How can we prevent these situations?

**Comment by OleksiienkoMykyta** [comment]
The [PR](https://github.com/apache/cassandra-gocql-driver/pull/1684) and the [Issue](https://github.com/apache/cassandra-gocql-driver/issues/1315) looks similar to the current topic and fixes it. 
@emile-tawfik I think this issue should be closed, what do you think?

**Comment by emile-tawfik** [comment]
After re-testing, look like it was been fixed. We can close this issue.

**Comment by OleksiienkoMykyta** [comment]
@emile-tawfik Thank you for the fast response and for re-testing it!
