### ISSUE TITLE
Token map different size to token ring panic

### ISSUE THREAD

**Issue by massousaC1** [apache/cassandra-gocql-driver#1316]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
2.1.17.1439

### What version of Gocql are you using?
Commit Hash 0680bfb96414f75bcbfea84ed075e7f40e4197a3

### What did you do?
1. Open a Session. 2. Execute 5 fairly substantial SELECT queries. 3. Close session. 4. Re-open Session. 5. Execute similar queries.
Using `gocql.TokenAwareHostPolicy(gocql.DCAwareRoundRobinPolicy("us-east-dsestorage"))` policy

### What did you expect to see?
Returned result sets.

### What did you see instead?

> panic: token map different size to token ring: got 192 expected 208
> 
> goroutine 291 [running]:
> plexus2/vendor/github.com/gocql/gocql.(*networkTopology).replicaMap(0xc04675a288, 0xc0451400e0, 0xd, 0xd, 0xc0006c7800, 0xd0, 0x100, 0x46fcd5)
> 	/root/go/src/plexus2/vendor/github.com/gocql/gocql/topology.go:210 +0x1348
> plexus2/vendor/github.com/gocql/gocql.(*tokenAwareHostPolicy).updateKeyspaceMetadata(0xc0002f8980, 0xc00036a820, 0xa)
> 	/root/go/src/plexus2/vendor/github.com/gocql/gocql/policies.go:447 +0x395
> plexus2/vendor/github.com/gocql/gocql.(*tokenAwareHostPolicy).AddHost(0xc0002f8980, 0xc00f3ebe00)
> 	/root/go/src/plexus2/vendor/github.com/gocql/gocql/policies.go:478 +0x6e
> plexus2/vendor/github.com/gocql/gocql.(*Session).addNewNode(0xc000a94e00, 0xc00f3ebe00)
> 	/root/go/src/plexus2/vendor/github.com/gocql/gocql/events.go:188 +0x9f
> plexus2/vendor/github.com/gocql/gocql.(*Session).handleNodeUp(0xc000a94e00, 0xc04c7b96c4, 0x4, 0x4, 0x2352, 0x0)
> 	/root/go/src/plexus2/vendor/github.com/gocql/gocql/events.go:273 +0x113
> plexus2/vendor/github.com/gocql/gocql.(*controlConn).setupConn(0xc0007a74c0, 0xc0009121e0, 0x3, 0x4)
> 	/root/go/src/plexus2/vendor/github.com/gocql/gocql/control.go:288 +0x161
> plexus2/vendor/github.com/gocql/gocql.(*controlConn).connect(0xc0007a74c0, 0xc047aed540, 0x3, 0x4, 0xc047aed540, 0x3)
> 	/root/go/src/plexus2/vendor/github.com/gocql/gocql/control.go:251 +0x1e2
> plexus2/vendor/github.com/gocql/gocql.(*Session).init(0xc000a94e00, 0xc00033c0e0, 0x0)
> 	/root/go/src/plexus2/vendor/github.com/gocql/gocql/session.go:198 +0x52d
> plexus2/vendor/github.com/gocql/gocql.NewSession(0xc0002cac80, 0x1, 0x1, 0x19e1667, 0x5, 0x3, 0x45d964b800, 0x23c34600, 0x2352, 0xc00036a820, ...)
> 	/root/go/src/plexus2/vendor/github.com/gocql/gocql/session.go:161 +0x824
> plexus2/vendor/github.com/gocql/gocql.(*ClusterConfig).CreateSession(...)
> 	/root/go/src/plexus2/vendor/github.com/gocql/gocql/cluster.go:185
> 

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
The cluster is fairly large, hosted in AWS across 24 nodes. We 2 data_center values, *us-east-dsestorage* and *us-west-2-2-dsestorage*

I raise this issue as we do not see the panic with gocql [PR#1227](https://github.com/gocql/gocql/pull/1227) nor [PR#1289](https://github.com/gocql/gocql/pull/1289) but do see it with [PR#1314](https://github.com/gocql/gocql/pull/1314)

- output of `SELECT peer, data_center, rpc_address FROM system.peers`
peer	data_center	rpc_address
/10.186.72.220	us-west-2-2-dsestorage	/10.186.72.220
/10.186.72.40	us-west-2-2-dsestorage	/10.186.72.40
/10.202.72.63	us-east-dsestorage	/10.202.72.63
/10.202.71.186	us-east-dsestorage	/10.202.71.186
/10.186.71.134	us-west-2-2-dsestorage	/10.186.71.134
/10.202.72.58	us-east-dsestorage	/10.202.72.58
/10.186.72.27	us-west-2-2-dsestorage	/10.186.72.27
/10.186.72.162	us-west-2-2-dsestorage	/10.186.72.162
/10.186.71.138	us-west-2-2-dsestorage	/10.186.71.138
/10.202.72.197	us-east-dsestorage	/10.202.72.197
/10.186.71.213	us-west-2-2-dsestorage	/10.186.71.213
/10.202.71.189	us-east-dsestorage	/10.202.71.189
/10.186.72.173	us-west-2-2-dsestorage	/10.186.72.173
/10.202.71.150	us-east-dsestorage	/10.202.71.150
/10.202.72.241	us-east-dsestorage	/10.202.72.241
/10.202.72.141	us-east-dsestorage	/10.202.72.141
/10.186.72.100	us-west-2-2-dsestorage	/10.186.72.100
/10.202.71.159	us-east-dsestorage	/10.202.71.159
/10.202.72.20	us-east-dsestorage	/10.202.72.20
/10.202.72.205	us-east-dsestorage	/10.202.72.205
/10.186.72.59	us-west-2-2-dsestorage	/10.186.72.59
/10.186.71.214	us-west-2-2-dsestorage	/10.186.71.214
/10.186.72.242	us-west-2-2-dsestorage	/10.186.72.242

Thank you

**Comment by martin-sucha** [comment]
I believe this might have the same underlying cause (race condition on add/remove host) as https://github.com/gocql/gocql/issues/1274

**Comment by yury-kozlov** [comment]
In my case the error message was very confusing: "token map different size to token ring: got 0 expected 768".
The cause of the issue was incorrect keyspace setup: it was defined with NetworkTopologyStrategy referencing wrong datacenter.

**Comment by martin-sucha** [comment]
@yury-kozlov Could you please open a separate issue and include the version of gocql you are using and steps to reproduce (what was incorrect with the keyspace setup)? Thanks!

**Comment by OleksiienkoMykyta** [comment]
As I see, [this pull request](https://github.com/apache/cassandra-gocql-driver/pull/1350) helps with it.
@massousaC1, have you had a chance to re-test it, or does the issue persist?

**Comment by joao-r-reis** [comment]
Closing due to a lack of response from the user, we can reopen it later if needed
