### ISSUE TITLE
Fuzzer panics (slice bounds out of range and makeslice len out of range)

### ISSUE THREAD

**Issue by bradleyjkemp** [apache/cassandra-gocql-driver#1367]
I ran the fuzz harness already in the codebase (https://github.com/gocql/gocql/blob/master/fuzz.go) and found two panics:

These can be reproduced using:
```go
package main

import "github.com/gocql/gocql"

var data = "<something>"

func main() {
	gocql.Fuzz([]byte(data))
}
```

When `data = "\x85000\x00\x00\x00\x00\x18\x00\x00\x13\x00\x00\x0000000000000000\x10000"`
This panics with stack trace:
```
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/gocql/gocql.(*framer).parseFrame.func1(0xc0000fbdf8)
	/Users/bradleykemp/src/github.com/gocql/gocql/frame.go:555 +0x173
panic(0x116dea0, 0x12b6ca0)
	/var/folders/zp/mxc6j46j0jb660hsh571y1mw0000gn/T/go-fuzz-build588435232/goroot/src/runtime/panic.go:522 +0x1b5
github.com/gocql/gocql.(*framer).readInetAdressOnly(0xc00011e000, 0x30303030, 0x1508f00, 0x20300000000000)
	/Users/bradleykemp/src/github.com/gocql/gocql/frame.go:1910 +0x605
github.com/gocql/gocql.(*framer).readErrorMap(0xc00011e000, 0x30303030)
	/Users/bradleykemp/src/github.com/gocql/gocql/frame.go:720 +0x91
github.com/gocql/gocql.(*framer).parseErrorFrame(0xc00011e000, 0x119f230, 0xc0000fbdf8)
	/Users/bradleykemp/src/github.com/gocql/gocql/frame.go:669 +0x6e3
github.com/gocql/gocql.(*framer).parseFrame(0xc00011e000, 0x0, 0x0, 0x0, 0x0)
	/Users/bradleykemp/src/github.com/gocql/gocql/frame.go:580 +0x3c3
github.com/gocql/gocql.Fuzz(0x4270000, 0x21, 0x21, 0x4)
	/Users/bradleykemp/src/github.com/gocql/gocql/fuzz.go:21 +0x2e0
go-fuzz-dep.Main(0xc0000fbf80, 0x1, 0x1)
	/var/folders/zp/mxc6j46j0jb660hsh571y1mw0000gn/T/go-fuzz-build588435232/goroot/src/go-fuzz-dep/main.go:30 +0x15b
main.main()
	/var/folders/zp/mxc6j46j0jb660hsh571y1mw0000gn/T/go-fuzz-build588435232/gopath/src/github.com/gocql/gocql/go.fuzz.main/main.go:15 +0x52
exit status 2
```

And when `data = "\x84000\b\x00\x00\x00\x12\x00\x00\x00\x04\x00\x0000000000\xfc000"`
This panics with stack trace:
```
panic: runtime error: makeslice: len out of range [recovered]
	panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/gocql/gocql.(*framer).parseFrame.func1(0xc0000f9dc0)
	/Users/bradleykemp/src/github.com/gocql/gocql/frame.go:551 +0x173
panic(0x1177ee0, 0x11cb870)
	runtime/panic.go:679 +0x1b2
github.com/gocql/gocql.(*framer).parsePreparedMetadata(0xc00011a000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/bradleykemp/src/github.com/gocql/gocql/frame.go:958 +0x83e
github.com/gocql/gocql.(*framer).parseResultPrepared(0xc00011a000, 0x4, 0x203000)
	/Users/bradleykemp/src/github.com/gocql/gocql/frame.go:1171 +0x8d
github.com/gocql/gocql.(*framer).parseResultFrame(0xc00011a000, 0x80, 0x12, 0x0, 0x0)
	/Users/bradleykemp/src/github.com/gocql/gocql/frame.go:1111 +0x31d
github.com/gocql/gocql.(*framer).parseFrame(0xc00011a000, 0x0, 0x0, 0x0, 0x0)
	/Users/bradleykemp/src/github.com/gocql/gocql/frame.go:580 +0x6d2
github.com/gocql/gocql.Fuzz(0x4110000, 0x1b, 0x1b, 0x4)
	/Users/bradleykemp/src/github.com/gocql/gocql/fuzz.go:21 +0x2e0
go-fuzz-dep.Main(0xc0000f9f48, 0x1, 0x1)
	go-fuzz-dep/main.go:30 +0x154
main.main()
	github.com/gocql/gocql/go.fuzz.main/main.go:15 +0x52
exit status 2
```

**Comment by OleksiienkoMykyta** [comment]
I tried to reproduce it but didn't succeed in it. 
@bradleyjkemp, Is it still relevant?

**Comment by joao-r-reis** [comment]
Closing due to a lack of response, we can reopen later if needed.
