### ISSUE TITLE
Nil pointer dereference and other panics due to race condition

### ISSUE THREAD

**Issue by creker** [apache/cassandra-gocql-driver#1381]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.11.6

### What version of Gocql are you using?
cd04bd7f22a72810d9eccd3ea334d898bf098576

### What did you do?
Here's reproducer

Schema
```sql
create keyspace t with replication = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
create table t(c1 text primary key);
insert into t(c1) values('1');
insert into t(c1) values('2');
insert into t(c1) values('3');
insert into t(c1) values('4');
```

Source
```go
package main

import (
	"github.com/gocql/gocql"
)

func query(session *gocql.Session) {
	var c1 string
	q := session.Query("select * from t").PageSize(2)
	defer q.Release()
	iter := q.Iter()
	count := 0
	for iter.Scan(&c1) {
		count++
		if count == 2 {
			break
		}
	}
	if err := iter.Close(); err != nil {
		panic(err)
	}
}

func main() {
	cluster := gocql.NewCluster("127.0.0.1")
	cluster.Keyspace = "t"
	session, err := cluster.CreateSession()
	if err != nil {
		panic(err)
	}

	go func() {
		for {
			query(session)
		}
	}()

	for {
		query(session)
	}
}
```

The following is important:
* Requests should execute in parallel
* Custom page size
* Iterating over rows but interrupting before next page. Other combinations of page size and count do not seem to work but I suspect this is due to how page prefetching works. In production I read single partition 1000 rows long and can reproduce the issue with count in range of 10 to 300. Everything else is working fine.

### What did you expect to see?
No panic

### What did you see instead?
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1268352]

goroutine 131 [running]:
github.com/gocql/gocql.(*queryMetrics).addAttempts(0x0, 0x1, 0xc000088780, 0x0)
        /Users/creker/Downloads/test/vendor/github.com/gocql/gocql/session.go:736 +0x22
github.com/gocql/gocql.(*Query).attempt(0xc00034e000, 0x130a148, 0x1, 0xbf750d7e77e91c40, 0xd1abeb2, 0x1524e60, 0xbf750d7e777c0e48, 0xcadb433, 0x1524e60, 0xc000168a20, ...)
        /Users/creker/Downloads/test/vendor/github.com/gocql/gocql/session.go:958 +0x60
github.com/gocql/gocql.(*queryExecutor).attemptQuery(0xc0000a6de0, 0x136eaa0, 0xc000092008, 0x1371aa0, 0xc00034e000, 0xc00015e200, 0x0)
        /Users/creker/Downloads/test/vendor/github.com/gocql/gocql/query_executor.go:32 +0x123
github.com/gocql/gocql.(*queryExecutor).do(0xc0000a6de0, 0x136eaa0, 0xc000092008, 0x1371aa0, 0xc00034e000, 0x0)
        /Users/creker/Downloads/test/vendor/github.com/gocql/gocql/query_executor.go:112 +0x1c0
github.com/gocql/gocql.(*queryExecutor).executeQuery(0xc0000a6de0, 0x1371aa0, 0xc00034e000, 0x0, 0x0, 0x0)
        /Users/creker/Downloads/test/vendor/github.com/gocql/gocql/query_executor.go:60 +0x437
github.com/gocql/gocql.(*Session).executeQuery(0xc000099880, 0xc00034e000, 0x0)
        /Users/creker/Downloads/test/vendor/github.com/gocql/gocql/session.go:431 +0xb7
github.com/gocql/gocql.(*nextIter).fetch.func1()
        /Users/creker/Downloads/test/vendor/github.com/gocql/gocql/session.go:1497 +0x3e
sync.(*Once).doSlow(0xc000080a90, 0xc0003577b0)
        /usr/local/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:57
github.com/gocql/gocql.(*nextIter).fetch(0xc000080a80, 0x1503e14)
        /Users/creker/Downloads/test/vendor/github.com/gocql/gocql/session.go:1496 +0x6e
created by github.com/gocql/gocql.(*Iter).Scan
        /Users/creker/Downloads/test/vendor/github.com/gocql/gocql/session.go:1394 +0x4cc
exit status 2
```

This is just one of the panic examples. In production I was able to get all kinds of panics. Here's a few more:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x348 pc=0x13c00ab]

goroutine 163 [running]:
sync.(*RWMutex).RLock(...)
        /usr/local/go/src/sync/rwmutex.go:48
github.com/gocql/gocql.(*Session).Closed(0x0, 0x100000001)
        /proj/vendor/github.com/gocql/gocql/session.go:419 +0x2b
github.com/gocql/gocql.(*Session).executeQuery(0x0, 0xc000169e60, 0xbc237a68bd389)
        /proj/vendor/github.com/gocql/gocql/session.go:427 +0x2f
github.com/gocql/gocql.(*nextIter).fetch.func1()
        /proj/vendor/github.com/gocql/gocql/session.go:1497 +0x3e
sync.(*Once).doSlow(0xc00021cdc0, 0xc00028cfb0)
        /usr/local/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:57
github.com/gocql/gocql.(*nextIter).fetch(0xc00021cdb0, 0x19189a0)
        /proj/vendor/github.com/gocql/gocql/session.go:1496 +0x6e
created by github.com/gocql/gocql.(*Iter).Scan
        /proj/vendor/github.com/gocql/gocql/session.go:1394 +0x4cc
exit status 2
```
```
panic: runtime error: index out of range [0] with length 0

goroutine 109 [running]:
github.com/gocql/gocql.createRoutingKey(0xc0000a51a0, 0x0, 0x0, 0x0, 0x34, 0xc0000a51a0, 0x0, 0x0, 0x0)
        /proj/vendor/github.com/gocql/gocql/session.go:1759 +0x420
github.com/gocql/gocql.(*Query).GetRoutingKey(0xc0002286c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /proj/vendor/github.com/gocql/gocql/session.go:1015 +0xf7
github.com/gocql/gocql.(*tokenAwareHostPolicy).Pick(0xc0001fd0a0, 0x1a54fc0, 0xc0002286c0, 0x0)
        /proj/vendor/github.com/gocql/gocql/policies.go:584 +0x52
github.com/gocql/gocql.(*queryExecutor).do(0xc00015f720, 0x1a4ab00, 0xc0000aa000, 0x1a54fc0, 0xc0002286c0, 0x0)
        /proj/vendor/github.com/gocql/gocql/query_executor.go:87 +0x63
github.com/gocql/gocql.(*queryExecutor).executeQuery(0xc00015f720, 0x1a54fc0, 0xc0002286c0, 0x0, 0x0, 0x0)
        /proj/vendor/github.com/gocql/gocql/query_executor.go:60 +0x437
github.com/gocql/gocql.(*Session).executeQuery(0xc000214380, 0xc0002286c0, 0xbc26296cd34fd)
        /proj/vendor/github.com/gocql/gocql/session.go:431 +0xb7
github.com/gocql/gocql.(*nextIter).fetch.func1()
        /proj/vendor/github.com/gocql/gocql/session.go:1497 +0x3e
sync.(*Once).doSlow(0xc00014f0f0, 0xc0002d9fb0)
        /usr/local/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:57
github.com/gocql/gocql.(*nextIter).fetch(0xc00014f0e0, 0x19189a0)
        /proj/vendor/github.com/gocql/gocql/session.go:1496 +0x6e
created by github.com/gocql/gocql.(*Iter).Scan
        /proj/vendor/github.com/gocql/gocql/session.go:1394 +0x4cc
exit status 2
```
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x13c05c8]

goroutine 150 [running]:
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:74
github.com/gocql/gocql.(*Session).routingKeyInfo(0x0, 0x1a4ab00, 0xc0000aa000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /proj/vendor/github.com/gocql/gocql/session.go:480 +0x58
github.com/gocql/gocql.(*Query).GetRoutingKey(0xc00021a360, 0x0, 0x0, 0x0, 0x0, 0x0)
        /proj/vendor/github.com/gocql/gocql/session.go:1010 +0x92
github.com/gocql/gocql.(*tokenAwareHostPolicy).Pick(0xc0001d25b0, 0x1a54fc0, 0xc00021a360, 0x0)
        /proj/vendor/github.com/gocql/gocql/policies.go:584 +0x52
github.com/gocql/gocql.(*queryExecutor).do(0xc0001ec020, 0x1a4ab00, 0xc0000aa000, 0x1a54fc0, 0xc00021a360, 0x0)
        /proj/vendor/github.com/gocql/gocql/query_executor.go:87 +0x63
github.com/gocql/gocql.(*queryExecutor).executeQuery(0xc0001ec020, 0x1a54fc0, 0xc00021a360, 0x0, 0x0, 0x0)
        /proj/vendor/github.com/gocql/gocql/query_executor.go:60 +0x437
github.com/gocql/gocql.(*Session).executeQuery(0xc0000d3500, 0xc00021a360, 0x0)
        /proj/vendor/github.com/gocql/gocql/session.go:431 +0xb7
github.com/gocql/gocql.(*nextIter).fetch.func1()
        /proj/vendor/github.com/gocql/gocql/session.go:1497 +0x3e
sync.(*Once).doSlow(0xc0001d9b10, 0xc0001e2fb0)
        /usr/local/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:57
github.com/gocql/gocql.(*nextIter).fetch(0xc0001d9b00, 0x19189a0)
        /proj/vendor/github.com/gocql/gocql/session.go:1496 +0x6e
created by github.com/gocql/gocql.(*Iter).Scan
        /proj/vendor/github.com/gocql/gocql/session.go:1394 +0x4cc
exit status 2
```

I suspect I could get a few more but they all would have the same origin as the above
```
created by github.com/gocql/gocql.(*Iter).Scan
        /proj/vendor/github.com/gocql/gocql/session.go:1394 +0x4cc
```

**Comment by mediocregopher** [comment]
I am seeing this panic (the first one on the original issue) happening in production as well, on commit `95d072f1b5bb` (current master):

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6ef1a2]

goroutine 287078759 [running]:
github.com/gocql/gocql.(*queryMetrics).addAttempts(0x0, 0x1, 0xc000421e00, 0xc0863de880)
        /home/mediocregopher/src/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200121121104-95d072f1b5bb/session.go:736 +0x22
github.com/gocql/gocql.(*Query).attempt(0xc0af1d1c20, 0xc0001dee20, 0xe, 0xbf820118090d82ff, 0x60c53f36f7d, 0x1382940, 0xbf820118077fea46, 0x60c5265d6de, 0x1382940, 0xc0b0818750, ...)
        /home/mediocregopher/src/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200121121104-95d072f1b5bb/session.go:958 +0x60
github.com/gocql/gocql.(*queryExecutor).attemptQuery(0xc00029c240, 0xe3d480, 0xc0d2b1d440, 0xe48d60, 0xc0af1d1c20, 0xc0003a5900, 0xc0592c2650)
        /home/mediocregopher/src/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200121121104-95d072f1b5bb/query_executor.go:32 +0x123
github.com/gocql/gocql.(*queryExecutor).do(0xc00029c240, 0xe3d480, 0xc0d2b1d440, 0xe48d60, 0xc0af1d1c20, 0x0)
        /home/mediocregopher/src/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200121121104-95d072f1b5bb/query_executor.go:112 +0x1c0
github.com/gocql/gocql.(*queryExecutor).executeQuery(0xc00029c240, 0xe48d60, 0xc0af1d1c20, 0x0, 0x0, 0x0)
        /home/mediocregopher/src/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200121121104-95d072f1b5bb/query_executor.go:60 +0x437
github.com/gocql/gocql.(*Session).executeQuery(0xc000288a80, 0xc0af1d1c20, 0xc05b8471b4)
        /home/mediocregopher/src/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200121121104-95d072f1b5bb/session.go:431 +0xb7
github.com/gocql/gocql.(*nextIter).fetch.func1()
        /home/mediocregopher/src/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200121121104-95d072f1b5bb/session.go:1497 +0x3e
sync.(*Once).doSlow(0xc03a6a65e0, 0xc0592c27b0)
        /usr/lib/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
        /usr/lib/go/src/sync/once.go:57
github.com/gocql/gocql.(*nextIter).fetch(0xc03a6a65d0, 0x7f80a6ad50d0)
        /home/mediocregopher/src/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200121121104-95d072f1b5bb/session.go:1496 +0x6e
created by github.com/gocql/gocql.(*Iter).Scan
        /home/mediocregopher/src/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200121121104-95d072f1b5bb/session.go:1394 +0x4cc
```

We have a long running script which is performing thousands of queries and reading tens of thousands of rows every second. The panic happens only after an hour or two of running the script, but does consistently happen. I'll look a little into the code and see if I can find out more.

**Comment by mediocregopher** [comment]
Based on that stacktrace it looks like `queryMetrics` is nil, but `addAttempts` is being called on it. I don't see any way that a `Query` could be being constructed with a nil `queryMetrics`. What is happening, I think, is that `Release` is being called on the `Query`, which has the side-effect of setting `queryMetrics` to nil, and then somehow `Iter.Scan` is being called again on that `Query` object.

I'm 99% sure our code is not calling `Iter.Scan` after calling `Release`, as all queries happen through this helper function:

```go
func (cql *CQL) InstrumentedQuery(
	ctx context.Context, metricsLabel string,
	query string, args []interface{},
	cb func(*gocql.Query) error,
) error {
        // some metrics stuff
	cqlQuery := cql.Session.Query(query, args...).WithContext(ctx)
	defer cqlQuery.Release()
	if err := cb(cqlQuery); err != nil {
                // some metrics stuff
		return errors.Trace(err)
	}
	return nil
}
```

All application logic happens within the callback `cb`. I don't understand the gocql code well enough yet to know if it's possible for some process internal to the driver to be calling `Scan` for some reason. I'm going to retry our long running process without calling `Release` and see what happens.

@creker can you confirm if your code is also calling `Release` on queries? That could help narrow this down.

**Comment by creker** [comment]
From what I can see, this is due to page prefetching or some other kind of speculative work. My code iterates over results but terminates before the end is reached. So Release is probably called while there's an in-flight request for next page of results causing a panic.

If the Release call is triggering it then maybe #1315 is also related.

**Comment by MarcMagnin** [comment]
I think I'm getting that one triggered by `Scan()` which looks related: 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x358 pc=0x9bb64b]

goroutine 33301 [running]:
github.com/gocql/gocql.(*Session).Closed(0x0, 0x449d7e)
        /home/marc/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200519160334-799061058e31/session.go:434 +0x2b
github.com/gocql/gocql.(*Session).executeQuery(0x0, 0xc0005e90e0, 0xc000b83004)
        /home/marc/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200519160334-799061058e31/session.go:442 +0x2f
github.com/gocql/gocql.(*nextIter).fetch.func1()
        /home/marc/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200519160334-799061058e31/session.go:1529 +0x3e
sync.(*Once).doSlow(0xc000b835a0, 0xc0006677b0)
        /usr/local/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:57
github.com/gocql/gocql.(*nextIter).fetch(0xc000b83590, 0xc0001902c0)
        /home/marc/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200519160334-799061058e31/session.go:1528 +0x6e
created by github.com/gocql/gocql.(*Iter).Scan
        /home/marc/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200519160334-799061058e31/session.go:1426 +0x4cc
```

**Comment by creker** [comment]
Just retested with latest Cassandra and gocql versions. Got the same panic immediately

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13b42f6]

goroutine 241 [running]:
github.com/gocql/gocql.(*queryMetrics).attempt(0x0, 0x1, 0x20a50d, 0xc000082c00, 0x14651e00, 0x2253ca0, 0x20a50d)
        /proj/vendor/github.com/gocql/gocql/session.go:778 +0x26
github.com/gocql/gocql.(*Query).attempt(0xc000128000, 0x1a74cb0, 0x5, 0xbfab7973268ed598, 0x1485c3e1, 0x2253ca0, 0xbfab7973266e2e38, 0x14651ed4, 0x2253ca0, 0xc0002de5a0, ...)
        /proj/vendor/github.com/gocql/gocql/session.go:991 +0xc9
github.com/gocql/gocql.(*queryExecutor).attemptQuery(0xc00020ae40, 0x1bdac60, 0xc0000a2000, 0x1bf1320, 0xc000128000, 0xc000320000, 0x0)
        /proj/vendor/github.com/gocql/gocql/query_executor.go:32 +0x123
github.com/gocql/gocql.(*queryExecutor).do(0xc00020ae40, 0x1bdac60, 0xc0000a2000, 0x1bf1320, 0xc000128000, 0x0)
        /proj/vendor/github.com/gocql/gocql/query_executor.go:112 +0x1c0
github.com/gocql/gocql.(*queryExecutor).executeQuery(0xc00020ae40, 0x1bf1320, 0xc000128000, 0x0, 0x0, 0x0)
        /proj/vendor/github.com/gocql/gocql/query_executor.go:60 +0x42e
github.com/gocql/gocql.(*Session).executeQuery(0xc000213500, 0xc000128000, 0x0)
        /proj/vendor/github.com/gocql/gocql/session.go:446 +0xb7
github.com/gocql/gocql.(*nextIter).fetch.func1()
        /proj/vendor/github.com/gocql/gocql/session.go:1529 +0x3e
sync.(*Once).doSlow(0xc0002d8ac0, 0xc000058fb0)
        /usr/local/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:57
github.com/gocql/gocql.(*nextIter).fetch(0xc0002d8ab0, 0xc000036218)
        /proj/vendor/github.com/gocql/gocql/session.go:1528 +0x6e
created by github.com/gocql/gocql.(*Iter).Scan
        /proj/vendor/github.com/gocql/gocql/session.go:1426 +0x4cc
exit status 2
```

**Comment by martin-sucha** [comment]
Not sure whether it's the same issue, but I found one data race when reading the code at:

https://github.com/gocql/gocql/blob/5913df4d474e0b2492a129d17bbb3c04537a15cd/conn.go#L1181

Speculative fetches are in a separate goroutine, so could hit this.

**Comment by OleksiienkoMykyta** [comment]
I have tried to reproduce it, but everything works just fine, maybe it's eliminated during the development process, as well as related issue(https://github.com/apache/cassandra-gocql-driver/issues/1315).
It would be great if someone who faced such an issue could retest it and confirm that everything passes smoothly, before closing it.

**Comment by joao-r-reis** [comment]
Closing for now, if someone is able to reproduce this then we can reopen it.

**Comment by nmorenor** [comment]
I still see this same issue, with a similar case from the description of this issue.

panic({0x104fb5780?, 0x1054f4a90?})
	/opt/homebrew/Cellar/go/1.24.1/libexec/src/runtime/panic.go:792 +0xf0
github.com/gocql/gocql.(*queryMetrics).attempt(0x0, 0x1, 0x11351d, 0x14000178300, 0x0)
	/Users/nacho/go/pkg/mod/github.com/gocql/gocql@v1.7.0/session.go:883 +0x38
github.com/gocql/gocql.(*Query).attempt(0x140004f0a00, {0x140000cb4f0, 0x6}, {0xc1f91c174d5f3f90, 0xdbfb9277, 0x105553ae0}, {0xc1f91c174d4e0950, 0xdbea5d5a, 0x105553ae0}, 0x140000ebc20, ...)
	/Users/nacho/go/pkg/mod/github.com/gocql/gocql@v1.7.0/session.go:1116 +0xac
github.com/gocql/gocql.(*queryExecutor).attemptQuery(0x1400048a360, {0x1050ae040, 0x10557d340}, {0x1050b11d0, 0x140004f0a00}, 0x140004f0000)
	/Users/nacho/go/pkg/mod/github.com/gocql/gocql@v1.7.0/query_executor.go:60 +0xfc
github.com/gocql/gocql.(*queryExecutor).do(0x1400048a360, {0x1050ae040, 0x10557d340}, {0x1050b11d0, 0x140004f0a00}, 0x140000cf780)
	/Users/nacho/go/pkg/mod/github.com/gocql/gocql@v1.7.0/query_executor.go:154 +0x17c
github.com/gocql/gocql.(*queryExecutor).executeQuery(0x1400048a360, {0x1050b11d0, 0x140004f0a00})
	/Users/nacho/go/pkg/mod/github.com/gocql/gocql@v1.7.0/query_executor.go:92 +0x11c
github.com/gocql/gocql.(*Session).executeQuery(0x140004cc408, 0x140004f0a00)
	/Users/nacho/go/pkg/mod/github.com/gocql/gocql@v1.7.0/session.go:546 +0x11c
github.com/gocql/gocql.(*Query).Iter(0x140004f0a00)
	/Users/nacho/go/pkg/mod/github.com/gocql/gocql@v1.7.0/session.go:1318 +0x174
github.com/scylladb/gocqlx/v3.(*Queryx).Iter(0x140008602d0)

I have a for look that is inserting a row on a table, after save I call a function with `go` to start a go routine where inside I query other table, process some data and then save the same table that called the `go` routine. I get this on the first read. 

my code is like

```
for _, myDto := range myDtos {
   handler.save(myDto)
}
```

handler save looks like

```
session := getSession(ctx)
q = myTable.InsertQuery(session).BindStruct(myDto)
defer q.Release()
err = q.ExecRelease()
go saveEventHandler.publish(&myEvent{
   dto: myDto
}
```

saveHandler

```
session := getSession(ctx)
query := session.Query(repo.myMetaDataTable.SelectAll()).PageSize(200).PageState([]byte{})
defer query.Release()

metadatas := []*venueModels.VenueMetadata{}
iter := query.Iter()
```

iter := query.Iter() triggers the issue, have this behavior all the time.

the handler save method first store the data on the table and start the `go` routine, if after handler.save(myDto) I add a `time.Sleep(1 * time.Second)` error goes away.

**Comment by joao-r-reis** [comment]
@nmorenor can you remove the calls to `query.Release` and see if the issue persists?
